[package]
name = "bitcoin-zmq"
version = "0.1.0"
authors = ["Harry L. Barber <hlbarber93@gmail.com>"]
edition = "2018"
license = "MIT"


[dependencies]
futures-zmq = "*"
zmq = "*"
futures = "*"
bus_queue = "*"
bytes = "*"

[dev-dependencies]
tokio = "*"
hex = "*"
